services:
  drone_sim:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: tubitak_drone_sim
    restart: unless-stopped
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    entrypoint: /home/droneuser/entrypoint.sh
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=0
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      - PYTORCH_ROCM_ARCH=gfx1030
      - HIP_VISIBLE_DEVICES=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/home/droneuser/.Xauthority:rw
      - .:/home/droneuser/proje
      - ./ardupilot_gazebo:/gz_ws/src/ardupilot_gazebo:rw
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    group_add:
      - video
      - "992"